Repository bloom-housing/bloom-detroit, pull requests merged in 2025-05, with the labels that each got.

#42 Release/2025 05 14
  api/prisma/seed-helpers/feature-flag-factory.ts
  api/prisma/seed-staging.ts
  api/src/dtos/auth/confirm.dto.ts
  api/src/dtos/auth/update-password.dto.ts
  api/src/dtos/listings/listing-feature.dto.ts
  api/src/dtos/listings/listings-filter-params.dto.ts
  api/src/enums/listings/filter-key-enum.ts
  api/src/services/listing.service.ts
  api/src/utilities/build-filter.ts
  api/src/utilities/build-order-by.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/integration/permission-tests/helpers.ts
  api/test/unit/services/listing.service.spec.ts
  api/test/unit/utilities/build-order-by.spec.ts
  api/tsconfig.json
  shared-helpers/__tests__/postmarkString.test.ts
  shared-helpers/package.json
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/types/backend-swagger.ts
  shared-helpers/src/utilities/formKeys.ts
  shared-helpers/src/utilities/postmarkString.ts
  sites/partners/__tests__/components/listings/ListingFormActions.test.tsx
  sites/partners/__tests__/pages/listings/[id]/index.test.tsx
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/cypress/fixtures/listing.json
  sites/partners/package.json
  sites/partners/src/components/listings/ListingFormActions.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/BuildingDetails.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/BuildingFeatures.tsx
  sites/partners/src/lib/listings/formTypes.ts
  sites/public/.env.template
  sites/public/__tests__/components/listing/listing_sections/Apply.test.tsx
  sites/public/next.config.js
  sites/public/package.json
  sites/public/src/components/listing/ListingViewSeedsHelpers.tsx
  sites/public/src/components/resources/Resources.module.scss
  sites/public/src/components/resources/Resources.tsx
  sites/public/src/layouts/application.module.scss
  sites/public/src/layouts/application.tsx
  sites/public/src/pages/account/application/[id]/index.tsx
  yarn.lock
Labels: 1 review needed

#39 feat: add housing basics page
  shared-helpers/src/locales/ar.json
  shared-helpers/src/locales/es.json
  sites/public/page_content/locale_overrides/ar.json
  sites/public/page_content/locale_overrides/bn.json
  sites/public/page_content/locale_overrides/es.json
  sites/public/page_content/locale_overrides/general.json
  sites/public/src/components/content-pages/HousingBasics.module.scss
  sites/public/src/components/content-pages/HousingBasics.tsx
  sites/public/src/components/resources/ResourceCard.tsx
  sites/public/src/components/shared/VideoCard.module.scss
  sites/public/src/components/shared/VideoCard.tsx
  sites/public/src/lib/translations.ts
  sites/public/src/pages/housing-basics.tsx
Labels: ready to merge

#40 feat: update Accessibility page to use Seeds header
  sites/public/src/pages/accessibility.tsx
Labels: ready to merge

#43 release: 2025-05-20
  api/prisma/seed-staging.ts
  api/scripts/setup-psql.sh
  api/src/dtos/listings/listing.dto.ts
  api/src/enums/feature-flags/feature-flags-enum.ts
  api/src/services/application-exporter.service.ts
  api/src/services/application.service.ts
  api/src/services/geocoding.service.ts
  api/src/utilities/application-export-helpers.ts
  api/test/unit/services/application-exporter.service.spec.ts
  api/test/unit/services/application.service.spec.ts
  api/test/unit/services/script-runner.service.spec.ts
  api/test/unit/services/translation.service.spec.ts
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/types/backend-swagger.ts
  shared-helpers/src/views/CustomIconMap.tsx
  shared-helpers/src/views/CustomIcons.tsx
  shared-helpers/src/views/components/BloomCard.module.scss
  shared-helpers/src/views/components/BloomCard.tsx
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailLeasingAgent.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/LeasingAgent.tsx
  sites/partners/src/lib/listings/formTypes.ts
  sites/public/.env.template
  sites/public/__tests__/components/listing/listing_sections/LeasingAgent.test.tsx
  sites/public/next.config.js
  sites/public/page_content/locale_overrides/general.json
  sites/public/src/components/account/ApplicationsView.tsx
  sites/public/src/components/account/FavoritesView.tsx
  sites/public/src/components/assistance/Assistance.module.scss
  sites/public/src/components/assistance/Assistance.tsx
  sites/public/src/components/browse/ListingCard.module.scss
  sites/public/src/components/browse/ListingCard.tsx
  sites/public/src/components/listing/ListingView.tsx
  sites/public/src/components/listing/ListingViewSeeds.tsx
  sites/public/src/components/listing/listing_sections/LeasingAgent.tsx
  sites/public/src/components/listing/listing_sections/MainDetails.module.scss
  sites/public/src/components/listing/listing_sections/MainDetails.tsx
  sites/public/src/lib/hooks.ts
  sites/public/src/pages/account/edit.tsx
  sites/public/src/pages/get-assistance.tsx
  yarn.lock
Labels: ready to merge

#41 Fix: update footer elements fonts
  sites/public/src/components/shared/CustomSiteFooter.module.scss
Labels: ready to merge

#45 feat: align public header options
  sites/public/page_content/locale_overrides/ar.json
  sites/public/page_content/locale_overrides/bn.json
  sites/public/page_content/locale_overrides/es.json
  sites/public/page_content/locale_overrides/general.json
  sites/public/src/components/content-pages/About.tsx
  sites/public/src/layouts/application.tsx
  sites/public/src/pages/about.tsx
Labels: needs changes

#44 feat: add Learn more homepage title
  shared-helpers/src/locales/ar.json
  shared-helpers/src/locales/bn.json
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/views/CustomIconMap.tsx
  sites/public/src/components/home/Home.tsx
Labels: ready to merge

#46 feat: release 5-27-25
  .circleci/config.yml
  api/prisma/seed-helpers/jurisdiction-factory.ts
  api/prisma/seed-staging.ts
  api/src/controllers/script-runner.controller.ts
  api/src/dtos/script-runner/data-transfer.dto.ts
  api/src/enums/feature-flags/feature-flags-enum.ts
  api/src/modules/script-runner.module.ts
  api/src/services/application-flagged-set.service.ts
  api/src/services/script-runner.service.ts
  api/src/utilities/build-user-where.ts
  api/test/unit/services/script-runner.service.spec.ts
  api/test/unit/services/user.service.spec.ts
  package.json
  shared-helpers/__tests__/testHelpers.ts
  shared-helpers/src/auth/AuthContext.ts
  shared-helpers/src/locales/ar.json
  shared-helpers/src/locales/bn.json
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/types/backend-swagger.ts
  shared-helpers/src/views/CustomIconMap.tsx
  sites/partners/__tests__/components/applications/sections/FormHouseholdMembers.test.tsx
  sites/partners/__tests__/components/listings/ListingFormActions.test.tsx
  sites/partners/__tests__/components/listings/PaperListingForm/index.test.tsx
  sites/partners/__tests__/components/listings/PaperListingForm/sections/CommunityType.test.tsx
  sites/partners/jest.config.js
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/ListingFormActions.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/CommunityType.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx
  sites/public/__tests__/pages/account/application/[id]/index.test.tsx
  sites/public/__tests__/pages/finder.test.tsx
  sites/public/cypress.config.ts
  sites/public/cypress/support/commands.js
  sites/public/jest.config.js
  sites/public/src/components/applications/SubmittedApplicationView.tsx
  sites/public/src/components/browse/ListingCard.tsx
  sites/public/src/components/finder/FinderMultiselectQuestion.module.scss
  sites/public/src/components/finder/FinderMultiselectQuestion.tsx
  sites/public/src/components/finder/FinderRentQuestion.module.scss
  sites/public/src/components/finder/FinderRentQuestion.tsx
  sites/public/src/components/finder/RentalsFinder.module.scss
  sites/public/src/components/finder/RentalsFinder.tsx
  sites/public/src/components/home/Home.tsx
  sites/public/src/components/home/HomeResources.module.scss
  sites/public/src/components/home/HomeResources.tsx
  sites/public/src/components/home/HomeSection.tsx
  sites/public/src/lib/applications/AppSubmissionContext.ts
  sites/public/src/pages/applications/start/choose-language.tsx
  sites/public/src/pages/finder.tsx
  sites/public/src/patterns/SiteHeader.tsx
  yarn.lock
Labels: ready to merge, release

#47 feat: filtering pt 2 + 3 (#4868)
  api/prisma/seed-helpers/listing-data/lakeview-villa.ts
  api/prisma/seed-helpers/listing-data/sunshine-flats.ts
  api/prisma/seed-staging.ts
  api/src/controllers/listing.controller.ts
  api/src/dtos/listings/listing-filter-key.dto.ts
  api/src/enums/feature-flags/feature-flags-enum.ts
  shared-helpers/package.json
  shared-helpers/src/locales/ar.json
  shared-helpers/src/locales/bn.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/package.json
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailUnits.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx
  sites/public/__tests__/components/browse/FilterDrawer.test.tsx
  sites/public/__tests__/components/browse/FilterDrawerHelpers.test.tsx
  sites/public/package.json
  sites/public/src/components/browse/FilterDrawer.module.scss
  sites/public/src/components/browse/FilterDrawer.tsx
  sites/public/src/components/browse/FilterDrawerHelpers.tsx
  sites/public/src/components/browse/ListingBrowse.tsx
  sites/public/src/components/listing/listing_sections/MainDetails.tsx
  sites/public/src/lib/helpers.tsx
  sites/public/src/lib/hooks.ts
  sites/public/src/pages/listings-closed.tsx
  sites/public/src/pages/listings.tsx
  yarn.lock
Labels: ready to merge
